<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJLPyKll\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJLPyKll/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJLPyKll.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJLPyKll\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJLPyKll\App_KernelDevDebugContainer([
    'container.build_hash' => 'JLPyKll',
    'container.build_id' => '77cac3e6',
    'container.build_time' => 1676877963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJLPyKll');
